# Generated by Django 4.1.3 on 2023-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module_template', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='somegismodel',
            name='int_property',
            field=models.IntegerField(),
        ),
    ]
