# Generated by Django 4.1.3 on 2023-01-11 14:56

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=15)),
                ('alias', models.CharField(max_length=50)),
                ('bbox', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Layer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=15)),
                ('alias', models.CharField(max_length=50)),
                ('ordering', models.IntegerField(max_length=5)),
                ('layer_type', models.CharField(choices=[('V', 'Vector'), ('R', 'Raster')], max_length=1)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geoportal_core.area')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=15)),
                ('alias', models.CharField(max_length=50)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoportal_core.layer')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleFeatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=15)),
                ('field_type', models.CharField(choices=[('INT', 'Integer'), ('STR', 'String'), ('RL', 'Real'), ('PNT', 'Point'), ('LS', 'LineString'), ('POL', 'Polygon')], max_length=3)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoportal_core.simplefeature')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.SlugField(max_length=15, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='layer',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoportal_core.module'),
        ),
        migrations.AddField(
            model_name='area',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoportal_core.module'),
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together={('name', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together={('name', 'module')},
        ),
    ]
